//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int IdLibro { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdAutor { get; set; }
        public Nullable<int> IdEditorial { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<int> IdEstadoLibro { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<double> PrecioUnitario { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> IdGenero { get; set; }
    
        public virtual Autor Autor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual EstadoLibro EstadoLibro { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
